import os
from typing import Any, TextIO

a_string = """

This is a multi line string

"""

VAR = 50  # A Variable

#####################

#### COMMENT #######

####################

# def add(a, b: int=10):
def check_if_odd(num):
    """
    Checks if number is odd

    Args:
        num :


    (Generated by docly)
    """
    return True if num % 2 != 0 else False
# return a * b


def check_even_numbers_in_a_list (base_list) -> list:
    """
    Checks that all numbers in a list are equal.

    Args:
        base_list :


    (Generated by docly)
    """
    return [a for a in base_list if a % 2 == 0]


def open_file(file_path) -> TextIO:
    """
    open a file

    Args:
        file_path :


    (Generated by docly)
    """
    return open(file_path, "r")


def add_tensors (t, t1) -> Any:
    """
    Add two tensors.

    Args:
        t :
        t1 :


    (Generated by docly)
    """
    return t + t1


def print_hello_greetings() -> None:
    """
    Emulate greeting.

    (Generated by docly)
    """
    print("Hello")


def echo_name(name) -> str:
    """
    Echo the given name.

    Args:
        name :


    (Generated by docly)
    """
    return f"Hello {name}"


if __name__ == "__main__":
    print(add(12, 12))


def area_rectangle(length, width) -> Any:
    """
    Return the area of a rectangle.

    Args:
        length :
        width :


    (Generated by docly)
    """
    if length < 0 or width < 0:
        raise ValueError("only accepts non-negative values")
    return length * width
